version: "3.7"
services:
  redis:
    image: redis:3.0.6
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev,test
    ports:
      - "5432:5432"
    volumes:
      - /Users/petereck/Desktop/Desktop_Cloud/Dev/Projects/bourbon-journal/scripts/docker-entrypoint-initdb.d
